apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
spec:
  selector:
    app: mysql-exporter
  ports:
  - name: metrics
    protocol: TCP
    port: 9104
    targetPort: 9104
  type: ClusterIP
